service:
  dis:
    endpoint: https://dis.cn-north-4.myhuaweicloud.com
    region: cn-north-4
    ak: VSXXUNEHDFLEHPY2GMK4
    sk: AhVkE0wW761U5j2hHqxuZS70peVqLv4YWyOZGpwQ
    projectId: 57762277c0e54546be534f72954ed8c4
    stream-channel:
      default: dis-0AjJ